language: ruby
rvm: 2.7.1
sudo: false
before_install:
- npm install netlify-cli -g
- gem install bundler
before_script:
- bundle exec rake tags
script: bundle exec jekyll build
after_script:
- bundle exec drumknott refresh
- ./bin/load_remotes
- ./bin/upload
env:
  global:
  - JEKYLL_ENV=production
