highligher: rouge
permalink: "/:year/:month/:day/:title.html"
paginate: 20
paginate_path: "/posts/:num/"
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate
sass:
  sass_dir: styles
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      section: "posts"
name: Freelancing Gods
url: https://freelancing-gods.com
author:
  name: Pat Allan
  uri: https://freelancing-gods.com/about.html
exclude:
  - bin
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
