highligher: pygments
permalink: "/:year/:month/:day/:title.html"
paginate: 20
paginate_path: "/posts/:num/"
gems:
  - jekyll-redirect-from
  - jekyll-feed
sass:
  sass_dir: styles
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      section: "posts"
name: Freelancing Gods
url: http://freelancing-gods.com
author:
  name: Pat Allan
  uri: http://freelancing-gods.com/about.html
