source 'https://rubygems.org'

gem 'rake'
gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-zopfli'
gem 'drumknott', '~> 0.4.0'
gem 'ruby-progressbar', '~> 1.8.1'
